<?php


namespace App\Core\FacadeBundle\v1\Services\Acl;


class AclUser extends AbstractAclUnit
{
    public function allowedView(): bool
    {
        return true;
    }

    public function allowedModify(): bool
    {
        return true;
    }

    public function allowedDelete(): bool
    {
        return false;
    }

    public function allowedCreate(): bool
    {
        return false;
    }

    public function hasFullControl(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}